- Cargo.toml
- hal-core/Cargo.toml
- hal-core/src/boot.rs
- hal-core/src/lib.rs
- hal-core/src/mem.rs
This is still *very* rough. @iximeow, I would love to hear your
thoughts.
> feat(hal-core): initial sketch of hal-core APIs

- hal-core/src/mem/page.rs
this fixes the build; im a dipshit
> fix(hal-core): fix compiler error in `as_slice_mut`

- .github/workflows/rust.yml
hopefully this works
Closes #24
> chore: add CI

- hal-x86_64/src/interrupt/pic.rs
we learned about the 8259 PIC sisters today
> improve documentation and they're sisters actually

- util/src/lib.rs
- util/src/trace.rs
> feat(util): add tools for trace formatting

- alloc/src/buddy.rs
this PR adds an impl of `GlobalAlloc` for `mycelium_alloc::buddy::Alloc`
so that we can reuse the buddy allocator as a heap allocator. no
functional change here.
in order to add this, i refactored the allocation code out of the
`page::Alloc` impl into inherent methods that operate on `Layout`s and
addrs, and reimplemented page allocation on top of that.
since we now operate on `Layout`s internally, we also rely on some of
their additional invariants.
note that i haven't actually tested this, but, like...it probably works?
> feat(alloc): impl `GlobalAlloc` for `buddy::Alloc`

- pci/src/class.rs
This also includes Display implementations for `iface::Ide`, however they're quite verbose to match the [OSDev Wiki](https://wiki.osdev.org/Pci#Class_Codes).
I'm unfortunately not super satisfied with the display format. Only the first attribute on each variant is checked, and must be a doc comment. See tests for examples.
> Autogenerate Display impls from doc comments

- hal-x86_64/src/interrupt/idt.rs
- hal-x86_64/src/segment.rs
- util/src/bits.rs
i'll rebase merge this one because it has a bunch of small commits in it
> rewrite IDT and segmentation code to use new bit packing stuff

- Cargo.lock
- hal-core/src/boot.rs
- hal-core/src/framebuffer.rs
- hal-core/src/lib.rs
- hal-x86_64/Cargo.toml
- hal-x86_64/src/framebuffer.rs
- hal-x86_64/src/framebuffer/embedded_graphics.rs
- hal-x86_64/src/lib.rs
- src/arch/x86_64.rs
- src/lib.rs
- util/src/macros.rs
- util/src/sync/once.rs
- util/src/sync/spin.rs
> quick framebuffer driver

- alloc/src/buddy.rs
this might help avoid stack overflows if we do a lot of splits and end
up with a deeply-nested stack.
> fix(alloc): make add_region loop instead of recursive

- hal-core/src/mem/page.rs
- hal-x86_64/src/mm.rs
- src/arch/x86_64.rs
- src/lib.rs
- trace/src/lib.rs
Clippy complains about these, so it's nice to get rid of them...
> refac: remove unnecessary borrows

- .github/workflows/ci.yml
- .github/workflows/ci_warnings.yml
- .github/workflows/cordyceps.yml
- .github/workflows/loom-util.yml
This changes the CI workflows to only run when the files they would test
have changed.
> chore(ci): make CI workflows smarter about when they run

- hal-x86_64/src/interrupt.rs
- src/arch/x86_64/oops.rs
It turns out that the reason we've been seeing extremely spooky behavior
in interrupt handlers, especially when trying to disassemble at `[rip]`,
is because LOL ELIZA FUCKED UP THE REGISTERS LOL LMAO.
When an interrupt occurs, a number of registers are pushed to the stack
frame for the interrupt handler. This includes the instruction pointer,
stack pointer, and the code and stack segment selectors. We defined a
`Registers` struct that consists of named fields for these registers, in
the correct order. However, because I'm a **loser fucking idiot**, the
current x86_64 ISRs were accidentally taking an `&mut Registers` rather
than a `Registers`. This meant we were interpreting the first 64 bits of
the registers (which I believe was the zero-padded 16-bit `ss` stack
segment selector) as a …
> fix(x86_64): unfuck interrupt stack frames

- alloc/src/buddy.rs
- hal-core/src/addr.rs
- trace/src/lib.rs
this contains several small changes to make debug output easier to read.
> make debug output more readable

- src/arch/x86_64/oops.rs
This cleans up the oops serial logs a bit, and makes the
disassembly look slightly nicer.
> feat(x86_64): make oops serial logs a bit prettier

- cordyceps/src/mpsc_queue.rs
> fix typo: incosistent -> inconsistent

- cordyceps/Cargo.toml
- cordyceps/README.md
- cordyceps/src/util.rs
As requested!
If this gets more complicated, it might be worth bringing in the `cfg_if` crate.
> Add cache padding inhibitor

- .github/FUNDING.yml
Since people are becoming interested in using some Mycelium crates
elsewhere, it seems worthwhile to add this. I'm happy to add other
contributors as well (cc @jamesmunns?) if anyone wants me to.
> chore: add `.github/FUNDING.yml`

- .github/workflows/cordyceps.yml
- .github/workflows/loom-util.yml
- .github/workflows/maitake.yml
> chore(ci): fix wrong path filters for loom jobs

- cordyceps/Cargo.toml
- maitake/Cargo.toml
> chore: add some more cargo metadata

- .github/workflows/ci.yml
- cordyceps/src/list.rs
- netlify.toml
> chore(ci): use `cargo-action-fmt`, add docs check

- cordyceps/README.md
- cordyceps/src/lib.rs
- cordyceps/src/list.rs
- cordyceps/src/mpsc_queue.rs
> docs(cordyceps): add basic linked list examples

- .github/workflows/release.yml
> chore: publish GitHub releases on tags

- Cargo.lock
- cordyceps/CHANGELOG.md
- cordyceps/Cargo.toml
> cordyceps: prepare to release v0.2.0

- bin/prep-release
- cliff.toml
> chore: add bash scripts to prep releases

- cordyceps/CHANGELOG.md
- cordyceps/Cargo.toml
> chore: prepare to release cordyceps 0.2.1

- bin/miri
Enable strict provenance checks from https://gankra.github.io/blah/tower-of-weakenings/#ok-but-what-the-heck-is-strict-provenance
> More Miri Checks!

- maitake/src/wait/cell.rs
There's currently a bug in `WaitCell::register_wait` where the `Closed`
error is returned if the `WaitCell` is woken during a register attempt.
I believe this was introduced in PR #223, due to a misunderstanding of
this line:
```rust
// Reset to the WAITING state by clearing everything *except*
// the closed bits (which must remain set).
let state = test_dbg!(self.fetch_and(State::CLOSED, AcqRel));
// The only valid state transition while we were parking is to
// add the CLOSED bit.
debug_assert!(
state == actual || state == actual | State::CLOSED,
"state changed unexpectedly while parking!"
);
```
This code does *not* set the `CLOSED` bit if it is not already set, it
just clears all other bits *except* the `CLOSED` bit. So, if the
`CLOSED` bit is not set, it remains unset, but if it is …
> fix(maitake): fix `WaitCell` returning `Closed` when woken

- maitake/src/task.rs
- maitake/src/task/builder.rs
- maitake/src/task/join_handle.rs
These were supposed to be added in #261 but I must have forgot to
commit them.
> docs(maitake): additional `task` and `JoinHandle` docs

- maitake/src/task.rs
- maitake/src/wait/cell.rs
- maitake/src/wait/queue.rs
- util/README.md
> docs(util): fix broken link in README.md

- maitake/src/lib.rs
- maitake/src/task.rs
- maitake/src/task/join_handle.rs
- maitake/src/task/state.rs
- maitake/src/task/tests.rs
thanks @jamesmunns for fixing my merge conflicts :)
> merge main into less-waker-vtables

- maitake/src/task.rs
- maitake/src/trace.rs
This (hopefully) makes the `fmt::Debug` output for the `Task` type a little bit
prettier and more readable.  
Before:
```
2022-07-30T18:59:11.589937Z DEBUG poll{task=TaskRef(0x7f073400b6a0)}: maitake::task: task=Task {
storage: maitake::task::storage::BoxStorage,
output_type: (),
scheduler_type: &maitake::scheduler::StaticScheduler,
header: Header {
run_queue: Links {
next: 0x00007f0734009000,
is_stub: false,
},
state: State {
POLLING: false,
WOKEN: false,
COMPLETED: false,
HAS_JOIN_HANDLE: false,
JOIN_WAKER: Empty,
HAS_OUTPUT: false,
REFS: 1,
},
vtable: Vtable {
poll: 0x00005624ed256bf0,
poll_join: 0x00005624ed29c8d0,
deallocate: 0x00005624ed281090,
},
span: Span {
span_01: Span {
name: "runtime.spawn",
level: Level(
Trace,
),
target: "maitake::task",
disabled: true,
module_path: …
```
> feat(maitake): nicer `fmt::Debug` impl for tasks

- maitake/src/scheduler.rs
- maitake/src/task.rs
- maitake/src/task/state.rs
The implementation of `Scheduler::current_task` added in #282 is
somewhat inefficient, as it performs an additional refcount
increment/decrement cycle on every poll. By refactoring how task polling
works a little bit, we can avoid this, by polling tasks through a
non-owning reference and making the `scheduler::Core` responsible for
post-poll cleanup. This way, the `Core` owns the `TaskRef` for the
entire poll, and can store the task in its `AtomicPtr` to the
currently-polled task without having to clone an additional reference.
This is essentially the approach I proposed in [this comment][1].
While making this change, I also cleaned up the post-poll state
transition code a little bit. The new implementation is slightly
simpler.
[1]: …
> perf(maitake): avoid ref cycle in scheduler's current task

- maitake/src/sync/wait_cell.rs
This is a separate branch from #304 because it actually changes API naming.
cc @jamesmunns any objections to this before i merge it? it will break some API type naming.
> chore(maitake): waitcell cleanup

- cordyceps/src/list.rs
This allows iterating over an owned list by value, in order to drain it. This is identical to the `IntoIterator` impl for
`std::collections::LinkedList`.
> feat(cordyceps): add by-value `IntoIterator` impl for `List`

- trace/src/lib.rs
This commit fixes an issue where nested spans were indented wrongly in
`tracing` output, and the wrong Unicode box drawing characters were used
when writing to the serial port. It also adds a delimiter character to
the framebuffer traces to make it more obvious when a span is entered.
This was factored out from #351 so that it can merge separately.
Before:
After:
> fix(trace): weird indentation on new spans

- src/shell.rs
These definitely should exist and are perfectly normal. Intended mainly for testing/demoing the fault- and panic-handling code without having to manually insert panics into the kernel.
> feat(kernel): add `panic` and `fault` shell commands

- Cargo.lock
- inoculate/Cargo.toml
- inoculate/src/lib.rs
- inoculate/src/qemu.rs
- inoculate/src/term.rs
This should hopefully fix the latest nightly.
> chore(inoculate): update to clap v4

- Cargo.lock
- Cargo.toml
- hal-x86_64/src/interrupt.rs
- hal-x86_64/src/interrupt/apic/io.rs
- hal-x86_64/src/interrupt/apic/local.rs
- hal-x86_64/src/mm.rs
- inoculate/Cargo.toml
- inoculate/src/lib.rs
- inoculate/src/main.rs
- inoculate/src/qemu.rs
- src/arch/x86_64.rs
- src/arch/x86_64/boot.rs
- src/arch/x86_64/framebuf.rs
- src/arch/x86_64/interrupt.rs
> update to `bootloader` v0.11.x

- maitake/src/task/tests/alloc_tests.rs
This makes the test for printing task sizes a bit fancier.
> test(maitake): add more stuff to task size test

- cordyceps/src/lib.rs
This PR adds a mention of SortedList to the top level docs
> docs(cordyceps): Add SortedList top level docs

- hal-x86_64/src/segment.rs
- justfile
somehow PR #542 automerged two weeks ago, despite tests failing. our CI situation is messed up. i gotta fix that. anyway here's wonderwall
> fix stuff that should have been in #542
