- hal-core/src/boot.rs
- hal-core/src/lib.rs
- hal-core/src/mem/mod.rs
- hal-x86_64/src/lib.rs
- src/arch/x86_64.rs
- src/lib.rs
depends on #27
the x64 kernel now reads the memory map from the bootloader and converts
it into our HAL types. i also implemented some unimplemented functions
in order to make this work.
> feat(x86_64): read memory map from bootloader

- pci/src/class.rs
Uses the `$v:vis` matcher to reduce some code duplication, and improves support for custom attributes.
> Small `class_enum!` tweaks

- hal-core/src/interrupt.rs
- hal-core/src/lib.rs
- hal-core/src/mem/mod.rs
- hal-core/src/mem/page.rs
- hal-x86_64/src/lib.rs
- src/arch/x86_64.rs
- src/lib.rs
- util/src/cell.rs
- util/src/sync/spin.rs
This fixes all clippy lints. Some of them were "fixed" by adding allow
attributes, but in those cases, I added comments explaining why we allow
those lints.
> style: placate clippy

- Cargo.toml
- alloc/Cargo.toml
- alloc/src/lib.rs
- src/arch/x86_64.rs
- src/lib.rs
- src/main.rs
I thought it might be useful to add a dummy kernel allocator, in case it is useful for building other components, before a proper paging abstraction is added to the `hal`. This allocator is about as dumb as it gets, providing only 640k of bump-allocating power, but allows the use of types like `Vec` in the kernel.
> feat(alloc): add a super basic and limited allocator

- Cargo.toml
- hal-x86_64/src/vga.rs
- src/arch/mod.rs
- src/arch/x86_64.rs
- src/lib.rs
- src/main.rs
- util/src/sync/spin.rs
This branch adds a (basic) kernel oops handler for when we do a
fucky-wucky. Right now it just makes a cool red screen of death 
and dumps a couple control registers, there's probably a lot of
additional state we should dump in here in the future.
Panics are also logged to serial prior to oopsing.
Right now it looks like this:
Fatal CPU exception ISRs should eventually call into oops directly,
rather than by panicking, so we can dump additional exception info.
Closes #49 (I'm assuming we will open follow-up issues for getting
more useful info on the oops screen).
> feat(kernel): dedicated kernel oops handler

- hal-core/src/addr.rs
- hal-core/src/boot.rs
- hal-core/src/interrupt/ctx.rs
- hal-core/src/interrupt/mod.rs
- hal-core/src/lib.rs
- hal-core/src/mem/mod.rs
- hal-core/src/mem/page.rs
- hal-x86_64/src/interrupt/mod.rs
- hal-x86_64/src/interrupt/pic.rs
- hal-x86_64/src/lib.rs
- hal-x86_64/src/vga.rs
- src/arch/mod.rs
- src/arch/x86_64.rs
- src/interrupt.rs
- src/lib.rs
- src/main.rs
The `Architecture` trait means that pretty much all downstream code that
consumes `hal-core` has to be parameterized over an architecture type,
which is kind of painful. `Architecture` pretty much only provides two
things: definitions of the `PAddr` and `VAddr` types, and an API
contract for architecture implementations.
On most architectures that we are likely to want to target, it's pretty
reasonable to represent `PAddr`s and `VAddr`s as words instead, using
`usize` as the inner repr. This means that for most architectures, HAL
implementations can still be written in separate crates without changing
`hal-core`. For architectures where we _do_ wish to add
architecture-specific logic in the address types, such as validating
that x86 addresses are in canonical form, or which require …
> refac(hal): do away with the Architecture trait

- hal-core/Cargo.toml
- hal-core/src/addr.rs
This branch makes the following changes:
* feat(hal-core): implement Address::{align_up, align_down}
Add generic default implementations of `align_up` and `align_down` to
all types implementing Address. These are implemented using a new 
required `from_usize` constructor.
* feat(hal-core): `Address::as_ptr` returns typed mut ptr
As discussed in [this comment][1], `as_ptr` now returns a `*mut T`
rather than a `*const ()`. It will now assert that the address is
correctly aligned for a `T`, using a new `is_aligned_for::<T>` 
convenience method.
* feat(hal-core): validate/canonicalize x86_64 addrs 
Add `#[cfg(target_arch = "x86_64")]` implementations of 
`Address::from_usize` for `PAddr`/`VAddr` that assert the address
is sign-extended/canonicalized when compiled in debug mode. 
Additionally, …
> feat(hal-core): address type improvements

- .github/workflows/rust.yml
This is a fairly flawed system, and currently won't ever actually rebuild the generated binaries, but may be acceptable. It appears to improve the performance of CI builds by about 2 minutes, from 5 minutes to 3 minutes.
> feat(ci): cache cargo-xbuild and bootimage binaries when running ci

- hal-core/src/interrupt/mod.rs
- hal-x86_64/Cargo.toml
- hal-x86_64/src/interrupt/mod.rs
- hal-x86_64/src/interrupt/pic.rs
- hal-x86_64/src/serial.rs
- src/arch/x86_64.rs
- src/lib.rs
- util/Cargo.toml
Currently, the kernel oops handler will forcibly unlock the VGA buffer
before writing the oops message. Ths prevents deadlocks if an oops
occurs while it was locked. However, we also write traces to COM1, but
we don't unlock it when oopsing.
This commit fixes this, by ensuring we forcibly unlock both VGA and
COM1 when oopsing. I also refactored the x64 ISRs a bit so that the
interrupt context for faults is printed by the oops function, rather than
by the ISR. This means we don't have to worry about force-unlocking
in multiple places.
> fix(x86_64): forcibly unlock COM1 when oopsing

- util/src/sync/mod.rs
- util/src/sync/spin.rs
This PR adds exponential backoffs to spin loops. When backing off, we
will issue an exponentially increasing number of `spin_loop_hint`s
(`pause` instructions on x86), up to 2^8 times per spin.
This may improve power consumption while spinning.
> feat(util): add exponential backoffs to spin loops

- hal-x86_64/src/control_regs.rs
- hal-x86_64/src/cpu.rs
- hal-x86_64/src/cpu/intrinsics.rs
- hal-x86_64/src/cpu/mod.rs
- hal-x86_64/src/interrupt/idt.rs
- hal-x86_64/src/interrupt/mod.rs
- hal-x86_64/src/lib.rs
- hal-x86_64/src/mm/mod.rs
- hal-x86_64/src/segment.rs
- src/arch/x86_64.rs
- src/lib.rs
This PR makes a few changes to inline assembly:
* Replace uses of the `asm!` macro, which is now deprecated, with the new `llvm_asm!` macro.
* Move inline assembly out of the kernel into HAL, adding new functions for current direct uses of inline assembly in the kernel 
The `hal-x86_64` crate now exposes a `cpu::intrinsics` module containing functions for emitting some assembly instructions without requiring inline assembly. In addition, I've added the ability to write a u32 to a `cpu::Port`, and a `cpu::halt` function for halting the CPU forever.
I'd like to make the `cpu::Port` better for writing things other than bytes, maybe w/ generics eventually....
> clean up inline asm

- hal-core/src/mem/page.rs
- hal-x86_64/src/control_regs.rs
- hal-x86_64/src/mm/mod.rs
Currently, the `Size` trait only allows representing statically known
sizes. This interface makes sense when _mapping_ pages, since the users
of that API will likely be saying things like "I want to map this 4kb
virtual page to a 4kb physical page". However, it makes less sense when
_translating_ pages/addresses. If I ask the page table "what page is
this address on?", I currently have to know in advance the size of the
page, which doesn't make sense — that's part of the information I would
be trying to _query_ by asking for the page containing an address. The
current trait does not model this nicely.
This commit updates the `Size` trait in `hal_core::mem::Page` to allow
representing dynamically sized pages, with a `Size::size()` fn rather
than an associated constant. The previous …
> feat(hal): allow representing dynamically sized pages

- hal-core/src/mem/mod.rs
- hal-core/src/mem/page.rs
- hal-x86_64/src/control_regs.rs
- hal-x86_64/src/interrupt/mod.rs
- hal-x86_64/src/interrupt/pic.rs
- hal-x86_64/src/mm/mod.rs
This fixes some annoying stuff in the mem APIs, makes end addrs
inclusive as expected, and implements a couple missing APIs. Factored
this out of [my page allocator PR][1], which will eventually be rebased
onto this.
[1]: https://github.com/hawkw/mycelium/tree/eliza/page-alloc
> page range, page, and mem region API tweaks & fixes

- .github/workflows/rust.yml
GitHub Actions has [deprecated the `add-path` command][1] which we are
currently using for caching `cargo install` binaries. This means our CI
builds are now failing.
This branch updates CI to use `actions-rs/install` for installing and
caching `cargo install` binaries instead. Hopefully this fixes CI.
Additionally, I've used YAML anchros to reduce repetition in the CI
configs.
Signed-off-by: Eliza Weisman <eliza@elizas.website>
> chore: don't use `add-path` for caching tools on CI

- .github/workflows/rust.yml
This PR changes the rustfmt and x86_64-mycelium `cargo check` CI steps
to not require the host `cargo check` step to pass before starting. This
way, we can run them in parallel, hopefully making CI builds complete a
little faster.
> chore: make CI run more stuff in parallel

- hal-x86_64/src/vga.rs
This used to compile but now rustc doesn't like it?
```
error[E0502]: cannot borrow `*self` as immutable because it is also borrowed as mutable
--> hal-x86_64/src/vga.rs:121:44
|
121 |         self.buf[self.row][self.col].write(self.character(ch));
|         ------------------           ----- ^^^^ immutable borrow occurs here
|         |                            |
|         |                            mutable borrow later used by call
|         mutable borrow occurs here
error: aborting due to previous error
```
> fix(hal-x86_64): fix VGA buffer compile error

- Cargo.lock
Apparently v0.9.11 doesn't compile on recent nightlies. Hopefully
v0.9.16 should...
> chore: update the `bootloader` crate

- .github/workflows/rust.yml
- Cargo.toml
Apparently `apt-get install qemu` *used* to provide the
`qemu-system-x86_64` binary, but maybe it doesn't anymore? Maybe
explicitly trying to install that package will fix CI?
> chore(ci): ensure the right qemu bin is installed

- util/src/intrusive/list.rs
In light of rust-lang/rust#82834, we must ensure that the intrusive
linked list pointers never get mutable-noalias optimizations (see also
rust-lang/rust#63818). Adding a `PhantomPinned` to the `Links` struct
ensures it will always be `!Unpin`, disabling mutable-noalias.
> fix(util): make intrusive list links never Unpin

- .github/workflows/ci_warnings.yml
The CI (warnings) job is broken because i copied and pasted in a check
from the main CI job, which still depends on another check in that
file. This fixes that, so the warnings job can run again.
> chore(ci): unbreak warnings thing

- util/proptest-regressions/bits.txt
- util/src/bits.rs
- util/src/lib.rs
this PR adds some nifty utilities for packing bits into integers. 
unlike some other bit-packing code that exists currently, these are
const-eval compatible: most bit packing/unpacking operations can be
performed in `const fn`, and when bit packing is performed at runtime,
the specs for packing and unpacking a particular bit range can be
defined in `const`s. this means that whenever possible, bit masks can be
computed at compile time, and the packing/unpacking ops that occur at
runtime are *just* a bitand/bitor and a shift. initially wrote them for
my double-fault TSS branch, but thought they should merge in a separate
PR beforehand.
> feat(util): add bit packing utilities

- util/src/bits.rs
This commit adds new "packing pair" APIs to `util::bits` to allow
packing from a bit range in one value to a bit range in a different
value (at a different offset), without shifting to the least significant
bit and back.
This does still perform two shifts (a shift right and a shift left).
However, one of those shifts will always be by 0 bits. When the packing
pair is a const, we expect that the release mode compiler will hopefully
eliminate the zero-bit shift. When the pair is _not_ a const, two shifts
is probably more efficient than storing a bool for whether we should
perform a shift left or a shift right and branching on it.
I also cleaned up some stuff in the bit packing code.
> feat(util): add packing pairs, other bit packing improvements

- Cargo.lock
- Cargo.toml
- src/arch/x86_64.rs
~we've talked about putting this in the oops fn, which i think would be much better, but by the time we're in `oops()` the only context we have is some `Display` thing. and even there, the cause we get is a call site is a `core::panic::Location`, which gets us a line and column of the offending source, but not an actual instruction pointer :(~
this punts decoding and displaying to the architecture-specific `oops` fn, i tried stitching it into `Context` in some form but trying to have a mutable iterator-shaped thing available from a `Context` is beyond what i have patience to get into the type system.
we might be able to do something with `backtrace` to get instruction pointers, and that probably lets us get function start addresses so we could actually disassemble some instructions before …
> decode x86 instructions around where we fault

- rust-toolchain.toml
- util/src/io/impls.rs
This just updates Rust to the latest nightly, and fixes a new Clippy
lint on that nightly.
> chore: update to nightly-2021-09-22, fix clippy

- rust-toolchain.toml
- util/src/io/impls.rs
- x86_64-mycelium.json
so, per @mystor, the nightly bump works if we switch to linking with GNU `ld`.
i spent a while struggling with trying to get rust-lld to work by passing the `-z nostart-stop-gc` argument, but `rust-lld` claims it doesn't know about that.
after adding this to the target JSON:
```json
"linker-flavor": "ld.lld",
"linker": "rust-lld",
"post-link-args": {
"ld.lld": [
"-z nostart-stop-gc"
]
},
```
i get
```
<...massive horrible linker invocation> "--gc-sections" "-z nostart-stop-gc"
= note: rust-lld: error: unknown -z value:  nostart-stop-gc
error: could not compile `mycelium-kernel` due to previous error
```
which seems surprising given that
> Require -z start-stop-gc, which is available in trunk ld.lld (https://reviews.llvm.org/D96914) and GNU ld newer than 2021-03-01 …
> chore: update nightly to 2021-09-22

- .gitignore
- default.nix
- shell.nix
It's nice to have gdb for debugging the kernel. This changes the
`nix-shell` config to ensure it's present in nix-shell, if the user
hasn't installed it globally.
I also added `.gdb_history` files to the gitignore.
> chore: add gdb to nix config

- .cargo/config
- inoculate/src/gdb.rs
- inoculate/src/lib.rs
- inoculate/src/main.rs
- inoculate/src/qemu.rs
This branch adds a separate subcommand to `inoculate` for launching
`gdb` and connecting to a running QEMU on the default port. This is
intended for when the QEMU has already been launched, and you want to
connect to it a second terminal. I've found this useful for running a
debug session while looking at serial output in the QEMU terminal.
> feat(inoculate): add subcommand for launching gdb

- inoculate/src/lib.rs
- inoculate/src/main.rs
- inoculate/src/qemu.rs
This branch includes a couple `inoculate` improvements:
- print paths in stderr output more like how cargo does, including stripping prefixes when possible
- fixed an issue where test summaries aren't printed due to an accidental early return
> feat(inoculate): nicer CLI output

- Cargo.lock
- hal-x86_64/src/interrupt.rs
- hal-x86_64/src/lib.rs
- inoculate/Cargo.toml
- rust-toolchain.toml
- util/src/intrusive/list.rs
- util/src/sync/spin.rs
update the toolchain to nightly-2021-09-22, fix new lints and stuff
> chore: update rust-toolchain to nightly-2021-09-22

- Cargo.lock
- inoculate/Cargo.toml
- inoculate/src/gdb.rs
- inoculate/src/lib.rs
- inoculate/src/main.rs
- inoculate/src/qemu.rs
- inoculate/src/term.rs
- inoculate/src/trace.rs
- mycotest/src/lib.rs
This branch adds a hacked-together `tracing` formatter for
cargo-esque logging in `inoculate`.
Some screenshots:
> feat(inoculate): `cargo`-style logs with `tracing`

- Cargo.lock
- Cargo.toml
- alloc/Cargo.toml
- alloc/src/buddy.rs
- alloc/src/bump.rs
- hal-core/Cargo.toml
- hal-x86_64/Cargo.toml
- hal-x86_64/src/serial.rs
- src/arch/x86_64.rs
- src/heap.rs
- src/lib.rs
- trace/Cargo.toml
- trace/src/lib.rs
- trace/src/writer.rs
- util/Cargo.toml
- util/src/fmt.rs
- util/src/intrusive/list.rs
Currently, mycelium contains two separate memory allocators: a bump
pointer allocator which is used as the kernel's heap allocator, and a
buddy-block allocator which is used to allocate physical pages for the
paging subsystem.
This is not ideal. The bump pointer allocator was intended primarily as
an interim solution until a better allocation scheme can be implemented
(and, secondarily, for potential use in early kernel initialization
before we can cut over to a proper allocator). It has a few significant
limitations: currently, it is limited in size to 640 KB, and (more
importantly) it cannot reclaim freed allocations. So, once those 640 KB
are used up, we are --- to use a technical term here --- "totally
fucked". If we want to make a number of heap allocations over the
kernel's …
> feat(kernel): use buddy block allocator for kernel malloc

- shell.nix
Apparently, the only difference between `qemu-full` and `qemu` is that
"full" enables ceph, smbd, and glusterfs support (see
https://twitter.com/witchof0x20/status/1477412443777294344?s=20). We
don't need any of that stuff; I had added `qemu-full` to the dev
nix-shell environment because I foolishly assumed "full" meant "all
architectures" or something.
This commit switches our `shell.nix` to just depend on `qemu` instead,
so we don't pull in all this other stuff we don't need.
> chore(nix): switch `qemu-full` to `qemu`

- .github/workflows/nightly.yml
This changes the GitHub Actions job that checks if mycelium builds on the
latest Rust nightly from a PR workflow to a cron job. This way, we don't
get the red X on PRs, because it's almost never the PR's fault that
nightly broke. Also, we won't miss potential nightly breakage if no
one's committing.
In the future, it could be nice to make this workflow automatically
update the pinned nightly if everything worked successfully. But, that
seems like a bit of work...
> chore(ci): move latest-nightly check to a cron job

- Cargo.lock
- Cargo.toml
- hal-x86_64/src/control_regs.rs
- hal-x86_64/src/cpu.rs
- hal-x86_64/src/cpu/intrinsics.rs
- hal-x86_64/src/interrupt.rs
- hal-x86_64/src/interrupt/idt.rs
- hal-x86_64/src/lib.rs
- hal-x86_64/src/mm.rs
- hal-x86_64/src/segment.rs
- rust-toolchain.toml
This branch updates Mycelium to build on Rust nightly 2022-02-15. This
appears to be the latest nightly that currently builds Mycelium; later
nightlies appear to introduce some weird issue where `rust-lld` attempts
to link with `libstdc++.so` and everything blows up. I don't super want
to figure that out right now.
In addition, this PR makes the following changes:
+ Update the use of the `asm!` macro to import it from `core::arch`,
which is now required.
+ Update the `wasmi` dep's use of the `asm!` macro to `core::arch::asm!`
(hawkw/wasmi@5caff845d5dbfdbdb82c624f470c55c71bfbe453)
+ Update the `bootloader` crate to v0.10.12, to ensure that it uses the
`asm!` macro correctly
Closes #132
> chore: bump nightly to 2022-02-15

- .github/workflows/cordyceps.yml
- alloc/src/buddy.rs
- bin/miri
- cordyceps/src/lib.rs
- cordyceps/src/list.rs
- cordyceps/src/mpsc_queue.rs
- rust-toolchain.toml
this branch adds a configuration for running Miri tests. currently, this
is primarily useful for testing `cordyceps` and friends, as the kernel
and HAL code contains a bunch of bare-metal stuff Miri definitely won't
understand.
after running Miri tests, i've fixed a number of stacked borrows
violations in the cordyceps linked list and MPSC queue modules. in
particular, i've changed the `Linked` trait a bit --- `Linked::as_ptr`
is now `Linked::into_ptr` and takes ownership of a `Handle`. this way,
we'll never produce an owning `Handle` (such as a `Box`) from a raw
pointer that originated from a shared reference (such as a
`&Pin<Box<...>>`). shared refs can still be used when the _handle type
itself_ is a shared ref. miri is now happy with us.
> fix(cordyceps): add miri tests, fix stacked borrows

- Cargo.lock
- Cargo.toml
- hal-x86_64/Cargo.toml
- hal-x86_64/src/framebuffer.rs
- hal-x86_64/src/vga.rs
- src/arch/x86_64.rs
- src/arch/x86_64/framebuf.rs
This commit changes the x86_64 kernel to use the `volatile` crate's
`Volatile` cell for the VGA buffer and framebuffer, rather than explicitly
using `ptr::write_volatile` and friends. This ensures all writes to the
these MMIO regions are volatile --- we can no longer accidentally
forget to use volatile reads/writes when accessing them.
> refac(x86_64): use `volatile` crate for MMIO

- .github/workflows/cordyceps.yml
> chore(ci): fix missing `steps` key for cordyceps

- bin/miri
This should let us only run miri tests for `cordyceps`, rather than other
random kernel code that we know miri won't like (since it does e.g.
MMIO).
> chore(ci): don't always pass `--workspace` to miri

- hal-core/src/framebuffer.rs
- hal-core/src/interrupt.rs
- hal-core/src/interrupt/ctx.rs
- hal-x86_64/src/interrupt.rs
- hal-x86_64/src/interrupt/idt.rs
- hal-x86_64/src/segment.rs
- hal-x86_64/src/vga.rs
- src/arch/x86_64.rs
- src/arch/x86_64/oops.rs
- src/lib.rs
- src/main.rs
- trace/src/embedded_graphics.rs
This branch rewrites the x86_64 oopsing code, making the following
changes:
- write to the framebuffer instead of the VGA buffer, so everything
looks nice
- put oopsing code in its own module and clean it up
- track whether we've panicked/faulted previously while handling an
oops
- disable yaxpeax disassembly for now since it appears to always cause
a general protection fault (???)
- add details to faults
- populate a bunch more code fault ISRs so they don't all double fault
A fault: 
A panic:
Rudimentary double panic handling:
> feat: bring back the Red Screen of uwu

- hal-core/src/interrupt/ctx.rs
- hal-x86_64/src/cpu.rs
- hal-x86_64/src/interrupt.rs
- hal-x86_64/src/segment.rs
- src/arch/x86_64.rs
The invalid TSS (0xA), segment not present (0xB), stack-segment
fault (0xC), and general protection fault (0xD) CPU exceptions push an
error code describing the segment selector that caused the fault. This
branch updates interrupt handling code to parse and display these error
codes nicely, and populates the invalid TSS, segment not present, and
stack-segment fault interrupt vectors with new ISRs.
In addition, the HAL "code fault" type now has a new optional `details`
method for passing an arbitrary `Display` payload to display in the oops
screen.
> feat(x86_64): display segment selector indices in faults

- mycotest/src/lib.rs
Currently, there is an error when compiling with the
`runner` feature disabled, as the module is not feature flagged,
but some of its dependencies are.
> fix(mycotest): fix missing runner feature flag

- .github/workflows/cordyceps.yml
- cordyceps/src/mpsc_queue.rs
These take *way* too long to run on CI. This branch makes them way
shorter.
> test(cordyceps): decrease # messages in loom tests

- .github/workflows/cordyceps.yml
- Cargo.lock
- async/Cargo.toml
- async/src/lib.rs
- async/src/loom.rs
- async/src/task/task_list.rs
- async/src/util.rs
- async/src/wait.rs
- async/src/wait/cell.rs
- bin/loom
- util/src/fmt.rs
This commit adds a `WaitCell` primitive to `mycelium-async`, which
stores a single waiter and notifies it.
> feat(async): add `WaitCell`

- .github/workflows/async.yml
- .github/workflows/ci.yml
- .github/workflows/ci_warnings.yml
- .github/workflows/cordyceps.yml
- .github/workflows/loom-util.yml
this fixes a stupid yaml mistake in the CI config for mycelium-async, and always runs CI on pushes to `main`
> fix CI yaml mistake

- async/Cargo.toml
- async/src/util.rs
- mycotest/src/report.rs
- src/arch/x86_64/oops.rs
- src/lib.rs
- src/wasm.rs
Rust 1.61 added new clippy lints. This fixes them:
* f1a2e86 fix dead code warnings in wasm module
* 26d897e fix nop let
* f4a34bc remove meaningless drop
* cd4ed95 remove meaningless `trim()` before `split_whitespace()`
* 7a01ed7 fix clippy re-export lint
> style: fix Rust 1.61 clippy lints

- Cargo.toml
- LICENSE
- alloc/Cargo.toml
- alloc/LICENSE
- async/Cargo.toml
- async/LICENSE
- bitfield/Cargo.toml
- cordyceps/LICENSE
- hal-core/Cargo.toml
- hal-core/LICENSE
- hal-multiboot2/LICENSE
- hal-x86_64/Cargo.toml
- hal-x86_64/LICENSE
- inoculate/Cargo.toml
- inoculate/LICENSE
- mycotest/Cargo.toml
- mycotest/LICENSE
apparently some people are actually interested in using bits of mycelium
for other projects, which is kind of shocking to me. to make that
possible, this branch adopts the MIT license for everything and adds
`LICENSE` files to every crate, so that when they're published to
crates.io, they'll be distributed along with a license.
Closes #169
> chore: adopt MIT license globally

- bitfield/src/bitfield.rs
> docs(bitfield): document generated methods

- bitfield/src/bitfield.rs
- bitfield/src/pack.rs
This branch changes bitfield packing specs to ensure that a field of a
given bitfield type may not be used to pack into/from a
bitfield of another type.
> feat(bitfield): packing spec type safety

- Cargo.lock
- async/Cargo.toml
- async/src/scheduler.rs
- async/src/task.rs
- async/src/task/state.rs
- async/src/util.rs
- async/src/wait.rs
- async/src/wait/cell.rs
this branch adds a proper implementation of task state transitions to
the async crate's task system. right now, the set of state transitions
is fairly small, but this will become more complex if we add
`JoinHandle`s or a similar abstraction for awaiting a task's completion.
also, i added tests exercising `wake_by_val` wakeups, and, it turns out,
we were leaking tasks in this case. so that's fixed now.
> feat(async): implement task state transitions

- maitake/src/scheduler.rs
- maitake/src/task.rs
> style(maitake): fix dead code warnings with loom

- maitake/src/task.rs
- maitake/src/task/state.rs
- maitake/src/task/tests.rs
these increment/decrement the task's reference count and can drop the
task if the dropped `TaskRef` is the last ref.
Will be needed for #184
Depends on #188
> feat(maitake): add`Clone`/`Drop` for `TaskRef`

- .github/workflows/ci.yml
- Cargo.lock
- bin/loom
- bitfield/src/bitfield.rs
- maitake/Cargo.toml
- maitake/src/lib.rs
- maitake/src/loom.rs
- maitake/src/scheduler/tests.rs
- maitake/src/util.rs
- maitake/src/wait.rs
- maitake/src/wait/queue.rs
- maitake/src/wait/queue/tests.rs
this branch adds a `WaitQueue` type in `maitake::wait`. this allows
multiple tasks to wait for an event, and be woken either one at a time
(in FIFO fashion), or all at once.
there are additional APIs we could add here, but this is a good starting
place. there probably should be docs examples but i'm lazy.
> feat(maitake): add `WaitQueue`

- cordyceps/src/list.rs
This PR adds some nice-to-have methods as detailed in [this issue](https://github.com/hawkw/mycelium/issues/186).
Changes:
* New `push_back` method
* New `pop_front` method
* Tests for each method
Small change but hope it's good :D
> feat(cordyceps): added new push_back and pop_front methods to list

- cordyceps/src/list.rs
> feat(cordyceps): add `List::len` method

- Cargo.lock
- cordyceps/Cargo.toml
- cordyceps/src/list.rs
- cordyceps/src/list/tests.rs
Currently, there is a potential safety issue when using
`cordyceps::list::IterMut`: the iterator's item type is `&mut T`.
`&mut T`s may be `mem::replace`d or `mem::take`en, moving them out of
the list to a different memory location. This would invalidate any
pointers in the list that point to that node.
Therefore, to ensure that the mutable iterator cannot corrupt the list
(potentially leading to dangling pointers or use-after-frees), this PR
changes `list::IterMut`'s `Item` type from `&'list mut T` to 
`Pin<&'list mut T`. This ensures that the iterator cannot be used to 
corrupt the list.
> fix(cordyceps): pin `list::IterMut` items

- cordyceps/src/list.rs
This branch adds accessors for the front and back elements of a
`cordyceps::List`. The returned elements are `Pin`ned to prevent them
from being moved out of the list. The `Pin`ning was not strictly
necessary for the immutable accessors but I did it for consistency with
the mutable ones...we _could_ safely just have those return `&T`,
though.
> feat(cordyceps): add `List::{front, back, front_mut, back_mut}`

- cordyceps/src/list.rs
- cordyceps/src/list/tests.rs
This branch adds a `List::drain_filter` iterator that moves items out of
the list if they match a predicate. This is based on the
[`drain_filter`] iterator on the `std::collections::LinkedList` type,
but modified slightly.
[`drain_filter`]: https://doc.rust-lang.org/stable/std/collections/struct.LinkedList.html#method.drain_filter
> feat(cordyceps): add `List::drain_filter`

- maitake/src/wait/map.rs
- maitake/src/wait/map/tests.rs
This includes the following changes:
Moves the uniqueness check from future creation point to
the time of enqueuing - otherwise you could have multiple
futures created with the same key, but not enqueued, that
would all be enqueued on their first poll. This also
removes the "try_wait" function, and "wait" can no longer
panic. In the duplicate case, the future will resolve to
an error instead.
Adds a EnqueueWait future that allows users to await ONLY
until the Wait has been enqueued in the actual WaitMap,
meaning they can then perform other operations without
a risk of racing with the expected response.
Corrected some incorrect documentation from the initial
Pull Request
Added tests for the above described behaviors
> A second round of additions to wait::WaitMap.

- maitake/src/lib.rs
- maitake/src/loom.rs
- maitake/src/sync.rs
- maitake/src/sync/mutex.rs
- maitake/src/sync/tests.rs
- maitake/src/sync/tests/loom_mutex.rs
- maitake/src/util.rs
- maitake/src/wait/queue.rs
- maitake/tests/mutex.rs
This branch adds an async `Mutex` type to `maitake`, implemented using
`WaitQueue`. The implementation should be pretty straightforward,
although it required adding some additional methods to `WaitQueue`.
Currently, all the new `WaitQueue` functions are `pub(crate)`, but I'm
open to making them public APIs as well; I just wanted to save that for
a separate PR.
The `Mutex` type lives in a new `maitake::sync` module for
synchronization primitives --- I was on the fence about whether it still
makes sense to have a separate `maitake::wait` module if we are going to
have `maitake::sync`, but I didn't want to put the mutex in `wait`, as
it does more than *just* notify waiting tasks. Perhaps the `wait` types
should be moved into `sync`, but I'd prefer to do that in a separate PR.
> feat(maitake): add an async `Mutex`

- maitake/src/wait/map/tests.rs
- maitake/src/wait/queue/tests.rs
- maitake/tests/mutex.rs
PR #219 added new tests for `maitake::sync::Mutex` that don't compile
when the "alloc" feature flag is not enabled. I forgot to make these
tests as `#[cfg(feature = "alloc")]`, so that PR broke the build with
`default-features = false`. Unfortunately, the CI job that tests with
`--no-default-features` was not marked as required, so although it
failed, PR #219 was still automerged and I didn't notice the build was
failing until it failed on `main`
(https://github.com/hawkw/mycelium/runs/6906013681?check_suite_focus=true)
This branch fixes the build failure by adding `cfg` attributes to the
tests that require the "alloc" feature. I also fixed some unused-imports
warnings in other tests that are only emitted with 
`default-features = false`.
> test(maitake): fix tests with `default-features = false`

- bin/miri
`cordyceps` and `maitake` currently contain code that perform
layout-dependent casts (in this case, casting a ptr to struct to a ptr
to the struct's first subfield), which would be UB if those structs
were not `#[repr(C)]`.
the `-Zrandomize-layout` flag tells the Rust compiler to randomize the
layout of all `#[repr(Rust)]` structs (see rust-lang/compiler-team#457
for details). if we ever perform a layout-dependent cast on a struct
that is not `#[repr(C)]` (or `#[repr(transparent)]`), layout
randomization would break that cast. enabling this flag while running
the Miri tests will help to catch any bugs introduced by accidentally
performing such a cast on a non-layout-dependent type.
i also made some changes to the `bin/miri` script. this was primarily to
add comments on the individual …
> test: run Miri with `RUSTFLAGS="-Zrandomize-layout"`

- cordyceps/src/lib.rs
- cordyceps/src/list.rs
- cordyceps/src/list/cursor.rs
- cordyceps/src/list/tests.rs
- cordyceps/src/list/tests/cursor.rs
This adds `List::append`, `List::split_off`, and `Cursor::split_before`/`split_after`.
> feat(cordyceps): add some list surgery methods

- cordyceps/src/list.rs
- cordyceps/src/list/cursor.rs
This commit renames `cordyceps::list::Cursor` to
`cordyceps::list::CursorMut`. This makes way for eventually introducing
an immutable `Cursor` type in 0.3 (once the deprecated type alias is
removed).
Deprecates `cordyceps::list::Cursor`.
DEPRECATED:
`cordyceps::list::Cursor` is deprecated, as it is now renamed to
`cordyceps::list::CursorMut`.
> feat(cordyceps): rename `list::Cursor` to `CursorMut`

- cordyceps/src/list/cursor.rs
Currently, the `Item` type of `list::CursorMut`'s `Iterator` impl is
`&mut T`. This is incorrect, as it allows the items to be moved out of
the list without unlinking them. Instead, the iterator's item type must
be `Pin`ned. PR #209 made this change for the `IterMut` type, but did
not make the same change for `CursorMut`, so this commit fixes
`CursorMut` similarly.
BREAKING CHANGE:
This changes the type signature of the `Iterator` impl for
`list::CursorMut`.
> fix(cordyceps): pin `CursorMut` iterator `Item`s

- cordyceps/src/list.rs
- cordyceps/src/list/cursor.rs
This branch adds an immutable cursor to `cordyceps::list`, in addition
to the existing mutable cursor. This functions similarly to the
`std::collections::linked_list::Cursor` type.
Depends on #240.
> feat(cordyceps): add immutable `list::Cursor` type

- Cargo.lock
- Cargo.toml
- maitake/Cargo.toml
- maitake/README.md
- maitake/src/scheduler.rs
- maitake/src/task.rs
- maitake/src/util.rs
- maitake/src/wait/cell.rs
This branch adds support for emitting both `tracing` 0.1 and `tracing`
0.2 diagnostics from Maitake. They are both controlled by feature flags,
which are additive --- both `tracing` versions _can_ be supported
simultaneously. The `tracing` configuration for tests still works as it
did previously.
The `tracing` 0.2 feature flag probably can't stay forever, if we ever
want to do a crates.io release of `maitake` before `tracing` 0.2 is
done...
> feat(maitake): add feature flags for both versions of `tracing`

- Cargo.lock
- maitake/src/scheduler.rs
- maitake/src/task.rs
- maitake/src/task/builder.rs
- maitake/tests/task_builder.rs
This branch adds a `task::Builder` API to `maitake` for configuring task
settings prior to spawning. Currently, the only settings that can be
configured are metadata fields used to populate the `tracing` span
generated for that task, such as a name (used for the `tokio-console`
`task.name` field).
This is similar to the (unstable) `task::Builder` API in `tokio`.
> feat(maitake): add a task builder for naming tasks

- cordyceps/src/mpsc_queue.rs
- maitake/src/task.rs
- maitake/src/util.rs
- util/src/sync/once.rs
These debug assertions were preventing builds in release mode.
> Fix debug asserts

- bitfield/src/lib.rs
_Personally, I'd just not allow `usize` at all, but since it already is, we should at least support 16 bit targets..._
I've rearranged primitive `FromBits` impls so that it's [clear that]
- `impl FromBits<T> for {u,i}size` is only supported on platforms with `size_of::<usize>() <= size_of::<T>()`
- `impl FromBits<{u,i}size> for T` is only supported on platforms with `size_of::<T>() <= size_of::<usize>()`
> fix(bitfield): respect 32 bit targets

- cordyceps/src/lib.rs
- cordyceps/src/list.rs
- cordyceps/src/list/tests.rs
- cordyceps/src/list/tests/owned_entry.rs
- cordyceps/src/mpsc_queue.rs
Currently, the `cordyceps` tests and docs show the use of a `#[repr(C)]`
struct with the `Links` field as the first member of the struct, and use
a cast from `NonNull<Self>` to `NonNull<Links<Self>>` in order to
implement the `Linked::links` method. This is done to avoid the creation
of a temporary reference by dereferencing the pointer and borrowing the
`Links` field, which Stacked Borrows dislikes.
This approach is not ideal for a couple of reasons:
* It performs a layout-dependent cast, and therefore *requires* the
`#[repr(C)]` attribute be present to ensure soundness. This means
that forgetting to add that attribute may result in miscompiles.
Also, relying on struct layout makes me feel uncomfortable and we
should try to avoid it where possible.
* It means that a given struct may not …
> docs(cordyceps): use `ptr::addr_of_mut!` instead of casts

- bitfield/src/pack.rs
There's currently a bug in the `raw_mask` method on
`mycelium-bitfield`'s packing spec types. `raw_mask` returns `self.mask`
shifted over by `self.shift`, with the intention of returning the actual
mask used by the packing spec. But...the `self.mask` field is already
shifted to the correct bit position, so shifting it in the `raw_mask`
method results in the mask being shifted over twice as many bits as it's
supposed to be.
This caused some *very* weird behavior in the `maitake` task state
management code, where attempting to toggle a bit using its `raw_mask`
would accidentally clobber low bits of the ref count, resulting in a
ref-count underflow in some cases.
> fix(bitfield): fix `raw_mask` shifting twice

- Cargo.lock
- maitake/Cargo.toml
- maitake/src/loom.rs
- maitake/src/scheduler.rs
- maitake/src/scheduler/tests.rs
- maitake/src/task.rs
- maitake/src/task/builder.rs
- maitake/src/task/join_handle.rs
- maitake/src/task/state.rs
- maitake/src/task/tests.rs
- maitake/src/trace.rs
- maitake/src/wait/cell.rs
- maitake/src/wait/map.rs
- maitake/src/wait/queue.rs
- maitake/tests/join_handle.rs
- maitake/tests/scheduler/alloc.rs
- maitake/tests/scheduler/custom_storage.rs
- src/tests.rs
This mostly works now, it probably needs more tests
> feat(maitake): implement `JoinHandle`s

- .github/workflows/ci.yml
- maitake/src/task.rs
- maitake/src/task/join_handle.rs
- util/src/sync/once.rs
A couple more issues showed up in release mode only.
Edit:
Added a basic `cargo check --release`, which I verified would have caught this regression.
Closes #273
> chore(maitake): Fix misc release mode errors

- maitake/src/task.rs
- util/src/lib.rs
- util/src/mem.rs
- util/src/mem/maybe_uninit.rs
- util/src/sync/once.rs
This branch adds a `mem::CheckedMaybeUninit` type in `mycelium-util`.
This is analogous to a `MaybeUninit`, except that, in debug mode builds,
it stores a flag tracking whether the memory location has been
initialized, and asserts that the flag is set when the memory location
is accessed. In release mode builds, this flag is not present.
This is intended to help ensure that uninitialized memory is used
correctly, while avoiding the potential overhead of tracking
initialization states in release builds.
Note that this is a somewhat more limited version of `MaybeUninit`:
because it stores only a single `bool` flag to track initialization, it
cannot be used to track element-by-element initialization of arrays. It
is usable only in cases where a single `T`-typed value may be
uninitialized. …
> feat(util): add a checked `MaybeUninit` cell

- maitake/src/lib.rs
- maitake/src/task.rs
- maitake/src/task/join_handle.rs
- maitake/src/task/state.rs
- maitake/src/task/tests.rs
Currently, `maitake`'s tasks store the `Waker` of any `JoinHandle` that
has polled the task using a `WaitCell`. This is somewhat inefficient, as
`WaitCell`s have their own atomic word of state, but only a couple bits
of state are actually needed to control access to the `Waker`.
Since `Task`s already have their own atomic word of state, we can reduce
the task's heap size significantly by changing from using a `WaitCell`
to just using a couple additional bits of the task's `StateCell` to
track the waiter's state. This gets rid of a word-sized atomic and (when
cache padding is enabled) that atomic's cache-line padding as well. By
storing the waker in a `MaybeUninit` instead of an `Option` (which is
fine here, as we will never set a waker again after consuming it), we
also avoid the …
> perf(maitake): don't use `WaitCell` for join wakers

- maitake/src/scheduler.rs
- maitake/src/scheduler/tests.rs
- maitake/src/task.rs
- maitake/src/task/builder.rs
- maitake/src/task/join_handle.rs
- maitake/src/task/tests.rs
This adds an initial implementation of a `Schedule::current_task` method
for cloning the currently-polled task. This implementation is somewhat
inefficient, as it has to perform an additional ref count clone/drop
cycle on every poll. This is unfortunately necessary because the current
task variable is not unset until the `TaskRef::poll` method returns, and
that method can drop the task, so we have to keep the task alive as long
as it's accessible through the scheduler (or else we risk handing out
`TaskRef`s pointed at deallocated tasks).
We can probably improve this by removing the unnecessary ref clone/drop
cycle, if we refactored how polling works a bit. If the scheduler unset
the current task variable _before_ a task is dropped, we wouldn't need
to clone the task before storing it in …
> feat(maitake): add `Schedule::current_task`

- maitake/src/scheduler.rs
This branch adds additional scheduler metric counters, including
counters of woken tasks, spawned tasks, etc.
We may want to feature-flag scheduler metrics, since they may have a
(very minor) performance cost. Currently, the `completed` counter is
used in tests, but we could feature-flag the rest. @jamesmunns what do
you think? Should these counters always be enabled?
> feat(maitake): track additional scheduler metrics

- bin/miri
- rust-toolchain.toml
`nextest` now has support for running Miri tests. This branch updates
the `bin/miri` script to use `cargo-nextest` if it is available. It was
also necessary to update the pinned Rust nightly to 2022-07-31 to pick
up nextest support in miri.
> chore: run `miri` tests using `cargo-nextest` when available

- CONTRIBUTING.md
- README.md
this commit moves the developer docs to `CONTRIBUTING.md` and adds new
README.md text explaining what Mycelium actually *is*.
> chore: move dev docs to CONTRIBUTING.md

- Cargo.lock
- Cargo.toml
- hal-x86_64/Cargo.toml
Version 0.4.5 of `volatile` includes the patches we needed from Git, so
the cargo patch to use a git dep can be removed.
> chore(hal): upgrade `volatile` to 0.4.5

- util/src/io/cursor.rs
This commit fixes a Clippy lint about `assert!`ing on
`Result::is_ok`/`Result::is_err` by using `expect`/`expect_err` instead.
No functional changes.
> style(util): fix clippy lints in `Cursor` tests

- Cargo.lock
- bitfield/src/pack.rs
- hal-x86_64/Cargo.toml
- hal-x86_64/src/cpu.rs
- hal-x86_64/src/segment.rs
This commit changes the `segment::Descriptor` implementation to use
`mycelium-bitfield` rather than `bitflags` + our packing specs. This
lets us remove the `bitflags` dep entirely.
> refac(hal-x86_64): use mycelium-bitfield for segment descrs

- maitake/src/task/id.rs
- maitake/src/task/join_handle.rs
A bunch of minor `JoinHandle`/`TaskID` API improvements:
* feat(maitake): add `PartialEq<TaskId>` impls for `JoinHandle`
`JoinHandle`s can currently be compared for equality with `TaskRef`s.
This commit allows comparing them with `TaskId`s as well.
* feat(maitake): implement `fmt::Display` for `JoinError`
This commit adds a nice `fmt::Display` implementation for `JoinError`.
* feat(maitake): add `TaskId`s to `JoinError`
This commit adds a `TaskId` field to the `JoinError` type, and a
`JoinError::id` method returning the ID of the task that failed to join.
This allows user code to determine which task errored.
* fix(maitake): `JoinHandle` `Debug` shouldn't require `T: Debug`
Currently, the `fmt::Debug` impl for `JoinHandle`s is derived. The
derived impl will require `T: fmt::Debug` for the …
> feat(maitake): minor joinhandle/taskid API improvements

- .config/nextest.toml
The `immediate-final` nextest config prints out output for failing tests
as soon as they fail, and also at the end of the run (for easy
scrollability). A lot of our tests, especially in `maitake`, will print
a bunch of logs on failure, so it's helpful to have the complete list of
failing tests printed *after* all the logs.
We used to only do this on CI. This branch changes the nextest config to
do it all the time.
> chore: always use `nextest`'s `immediate-final` failure output

- maitake/src/loom.rs
- maitake/src/sync.rs
- maitake/src/sync/mutex.rs
- maitake/src/sync/rwlock.rs
- maitake/src/sync/rwlock/loom.rs
- maitake/src/sync/rwlock/tests.rs
- maitake/src/sync/semaphore/tests.rs
- maitake/src/util.rs
This branch adds an async read-write lock implementation in
`maitake::sync`. This lock is implemented using the `Semaphore` type
added in #301. The rwlock is modeled using a `Semaphore` with
`Semaphore::MAX_PERMITS` permits in it; a reader must acquire a single
permit to gain read access, while a writer must acquire all the permits.
> feat(maitake): add `maitake::sync::RwLock`

- .config/nextest.toml
It turns out the `failure-output = "immediate-final"` option in
`nextest.toml` didn't do what I thought it did. It actually tells
Nextest to print all the _output_ from failing tasks at the end of the
run, while I thought that it just told Nextest to print the list of
_which tasks failed_ at the end of the run. It turns out that this is
controlled by a different setting, `final-status-level`.
This commit changes `.config/nextest.toml` to do what I _thought_ I was
configuring it to do all along.
> chore: fix nextest failure output

- cordyceps/src/list.rs
This enables additional optimizations if these iterators are guaranteed
to never return `Some` again after returning `None` once, which they
are.
> feat(cordyceps): add `FusedIterator` impls for `List` iterators

- maitake/src/scheduler.rs
- maitake/tests/scheduler/custom_storage.rs
This branch adds a new macro in `maitake` for safely initializing `StaticScheduler` instances in a `static` variable. The `StaticScheduler::new_with_static_stub` constructor is unsafe to call, because the stub task may not be shared between `StaticScheduler` instances.
The macro solves this by creating a `static TASK_STUB` variable inside a scope where the `StaticScheduler` is initialized. Due to macro hygeine, the `TASK_STUB` variable cannot be referenced outside of that scope, ensuring that it can't be used by multiple `StaticScheduler` instances.
Now, a `StaticScheduler` can be constructed like this:
```rust
use maitake::scheduler::{self, StaticScheduler};
// look ma, no `unsafe`!
static SCHEDULER: StaticScheduler = scheduler::new_static!();
```
> feat(maitake): add `scheduler::new_static!` macro

- src/arch/x86_64.rs
- src/arch/x86_64/interrupt.rs
- src/lib.rs
- src/rt.rs
Depends on #311 
This branch adds a kernel main loop with a Maitake timer and scheduler. We can spawn some `sleep` futures and IT WORKS!
> feat(kernel): use maitake timer and scheduler in mycelium

- maitake/src/loom.rs
- maitake/src/task.rs
- maitake/src/task/join_handle.rs
- maitake/src/task/state.rs
- maitake/src/task/tests.rs
- maitake/src/util.rs
This branch implements cancellation for spawned tasks. A task can be
cancelled through its `JoinHandle` (`JoinHandle::cancel`), or through a
`TaskRef` to it (`TaskRef::cancel`). When a task is cancelled, a bit is
set on its state field indicating that it has been canceled, and the
task is woken.
A leaf future inside a task can cancel that task by calling
`Scheduler::current_task()` to get a `Taskref` to itself, and then
canceling that `TaskRef`.
When the scheduler polls a task with the canceled bit set, it doesn't
poll the future, but instead notifies the task's `JoinHandle` and drops
its own reference to that task. Once the `JoinHandle` and all `TaskRef`s
that own reference counts for that task are dropped, the task can be
deallocated.
A task may be canceled in a state where the `Future` …
> feat(maitake): implement cancel culture for tasks

- Cargo.lock
- hal-x86_64/Cargo.toml
- hal-x86_64/src/cpu.rs
- hal-x86_64/src/cpu/entropy.rs
- hal-x86_64/src/cpu/intrinsics.rs
- hal-x86_64/src/cpu/tsc.rs
- src/arch/x86_64.rs
- src/arch/x86_64/entropy.rs
This branch adds a `hal_x86_64::cpu::entropy` module, with support for
generating entropy from hardware entropy sources in order to seed a
random number generator.
Entropy is sourced from the following entropy sources:
- The `rdrand` instruction, if the CPU supports it
- The `rdtsc` instruction, if the CPU supports it
- PIT timer channels 1-3, which are always available
> feat(hal_x86_64): add `cpu::entropy` module

- Cargo.lock
- Cargo.toml
This updates the `bootloader` crate to version 0.10.13, which fixes issues when booting on systems that report memory regions at high physical addresses in their memory map (see rust-osdev/bootloader#259).
This should make it possible to run Mycelium in QEMU v7.1.0 and later, without very poor boot performance, as well as on real hardware which reports high addresses (many AMD systems).
In addition, there are some new bootloader features we might want to play around with.
Fixes #321.
> fix(x86_64): update `bootloader` to 0.10.13

- justfile
- maitake/src/scheduler.rs
This branch enables `#[warn(missing_docs)]` in the `maitake::scheduler`
module, and adds a bunch of new documentation. I also fixed a minor
issue in the `justfile` where running `just docs` didn't set
`RUSTDOCFLAGS="--cfg docsrs"` so the README wasn't included in the docs
build.
> docs(maitake): document the `scheduler` module

- alloc/src/buddy.rs
- bitfield/src/pack.rs
- cordyceps/src/list.rs
- cordyceps/src/list/cursor.rs
- cordyceps/src/mpsc_queue.rs
- hal-core/src/interrupt.rs
- hal-core/src/mem.rs
- hal-core/src/mem/page.rs
- hal-x86_64/src/cpu.rs
- hal-x86_64/src/framebuffer.rs
- hal-x86_64/src/interrupt.rs
- hal-x86_64/src/interrupt/idt.rs
- hal-x86_64/src/task.rs
- hal-x86_64/src/vga.rs
- maitake/src/sync/mutex.rs
- maitake/src/sync/rwlock.rs
- maitake/src/task.rs
- maitake/src/time/timer/sleep.rs
- maitake/src/time/timer/wheel.rs
- mycotest/src/assert.rs
- mycotest/src/lib.rs
By using an exhaustive destructuring in manual `fmt::Debug` impls, we
get a compiler error if an additional field is added to a type with a
manual `Debug` impl which is not used in the `Debug` impl. This is nice,
since it helps guard against accidentally adding a field without
formatting it.
I've applied this refactoring to *most* manual `Debug` impls, with the
exception of a few that do something more weird than just manually
printing all the `Debug`-able field values.
This caught at least one case where I had forgotten to add a field to a
`Debug` impl :)
Thanks to Twitter User @cratelyn for this idea <3
> refac: use exhaustive bindings manual `fmt::Debug` impls

- .github/workflows/nightly.yml
Currently, the "latest nightly" CI cronjob only runs clippy checks. This
doesn't catch issues where nightly breaks actually compiling the kernel
image.
This branch updates the nightly CI workflow to actually build a bootable
mycelium image, so that we can catch issues like
rust-osdev/bootloader#271 earlier, instead of having to wait until I
manually try to update nightly.
> chore(ci): actually build a kernel image on nightlies

- trace/src/embedded_graphics.rs
this is significantly less eye-hurty, imo.
> feat(trace): make framebuffer trace text 6x13px

- src/arch/x86_64/boot.rs
- src/arch/x86_64/oops.rs
- trace/Cargo.toml
- trace/src/color.rs
- trace/src/embedded_graphics.rs
- trace/src/lib.rs
- trace/src/writer.rs
This branch makes the serial port and framebuffer traces a bit prettier,
including adding support for colors (either by setting the color for
drawing pixels to the framebuffer, or sending ANSI escapes on the serial
port). Eventually it might be nice if we only sent the serial port ANSI
escapes if the attached host told us it supports them, but meh.
Traces look like this now:
> feat(trace): make traces prettier, add colors

- hal-x86_64/src/cpu.rs
- hal-x86_64/src/cpu/msr.rs
This commit adds a `hal_x86_64::cpu::Msr` type for accessing x86 model-specific registers, either as raw integer values or as typed values using the `mycelium_bitfield::FromBits` trait.
Currently, a special constructor is provided for accessing the `IA32_APIC_BASE` MSR, which is needed for APIC interrupt handling. Similar typed constructors for other MSRs will be added in future PRs.
This PR was factored out from #351 (which implements APIC interrupt handling) so that it can be merged in a separate commit.
> feat(hal-x86_64): add `cpu::Msr` type for accessing MSRs

- hal-x86_64/src/cpu.rs
- hal-x86_64/src/cpu/entropy.rs
- hal-x86_64/src/interrupt.rs
- hal-x86_64/src/lib.rs
- hal-x86_64/src/time.rs
- hal-x86_64/src/time/pit.rs
- hal-x86_64/src/time/tsc.rs
This commit moves the `pit` and `tsc` modules out of `interrupt` and `cpu`, and into a new `time` module. This feels like a better organization of things, IMO.
> refac(hal-x86_64): move `pit` and `tsc` into `time`

- Cargo.lock
- trace/Cargo.toml
- trace/src/buf.rs
- trace/src/lib.rs
This branch adds a `LineBuf` type in `mycelium-trace`, which implements
a ring buffer of fixed-size text lines. This is intended for use as a
future scrollback buffer for the framebuffer logging output.
> feat(trace): add `LineBuf`

- alloc/src/bump.rs
- src/allocator.rs
- src/arch/x86_64/oops.rs
At one point in time, Mycelium contained a bump pointer allocator that
could be used for very early allocations before a better heap allocator
is initialized with information from the BIOS memory map. This was
removed in #130, since it was possible to use the buddy-block allocator
for all heap allocations.
In order to add a scrollback capability to framebuffer logging (#364),
though, we want to be able to allocate a dynamically sized scrollback
buffer. This is because we don't know the actual size of the framebuffer
at compile time, and need to determine how long the lines in the
scrollback ring are based on the dimensions of the framebuffer. However,
we want to preallocate the entire scrollback ring, since we want to be
able to store logs from inside the allocator in the scrollback ring. …
> feat(kernel): put back bump pointer region

- alloc/src/buddy.rs
- build.rs
- cordyceps/src/list.rs
- cordyceps/src/list/cursor.rs
- hal-core/src/addr.rs
- hal-x86_64/src/interrupt/idt.rs
- hal-x86_64/src/vga.rs
- inoculate/src/lib.rs
- justfile
- maitake/src/scheduler/steal.rs
- maitake/src/sync/wait_cell.rs
- maitake/src/sync/wait_map/tests/loom.rs
- maitake/src/time/timer/sleep.rs
- maitake/src/time/timer/wheel.rs
- maitake/src/time/timer/wheel/tests.rs
- mycotest/src/assert.rs
- mycotest/src/report.rs
- rust-toolchain.toml
- src/allocator.rs
- src/arch/x86_64/framebuf.rs
- util/src/math.rs
This commit updates Mycelium's pinned nightly version to Rust `nightly-2022-10-09`. Unfortunately, this currently doesn't work, due to linker errors when linking with the bootloader (see rust-osdev/bootloader#271).
> chore: roll nightly to `2022-10-07`

- maitake/src/sync/wait_queue.rs
This branch adds new methods to the `Wait` future returned by `WaitQueue`s for testing whether a `Wait` future is waiting on a particular queue instance.
`Wait::waits_on` takes a `&WaitQueue`, and returns `true` if the `Wait` future came from that queue, while `Wait::same_queue` takes another `&Wait` and returns `true` if the two `Wait` futures are waiting on the same `WaitQueue` or not.
I just thought these could potentially be nice to have.
> feat(maitake): add `Wait::{waits_on, same_queue}`

- hal-x86_64/src/interrupt/idt.rs
- src/arch/x86_64/shell.rs
- src/lib.rs
- src/shell.rs
this branch adds a `sleep` command for spawning  tasks that sleep for a number of seconds, for demoing/testing the timer wheel. in addition, it refactors the command-parsing code and prettifies the output for shell commands and error handling.
> more shell commands + fixups

- Cargo.lock
- maitake/Cargo.toml
- maitake/README.md
- maitake/src/loom.rs
- maitake/src/task/id.rs
- maitake/src/util.rs
This replaces the fallback implementation of task IDs using a `Mutex<u64>` on platforms without 64-bit atomics with the `portable_atomic` crate's `AtomicU64`. `portable_atomic`'s fallback impl uses a sequence lock, which should be more efficient than a spinlock.
> feat(maitake): use `portable_atomic` for task IDs

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
Apparently the extractions/setup-just action gets rate-limited by the GitHub API a lot, and adding an auth token fixes this: https://github.com/extractions/setup-just#examples
> chore(ci): fix `setup-just` rate limiting

- .config/nextest.toml
It's nice to see all the test results, rather than just the first failure.
> chore: disable failfast in local nextest runs

- maitake/Cargo.toml
- maitake/README.md
- maitake/src/lib.rs
- maitake/src/sync.rs
- maitake/src/sync/semaphore.rs
- maitake/src/sync/wait_map.rs
- maitake/src/task/join_handle.rs
- maitake/src/time/timeout.rs
- maitake/src/time/timer.rs
This branch adds implementations of the `core::error::Error` trait for
`maitake`'s error types. This is feature flagged, as it requires a
nightly Rust toolchain.
> feat(maitake): add feature-flagged `core::error::Error` impls

- hal-x86_64/src/interrupt.rs
The interrupt controller is stored in an `InitOnce` cell, so that it may be accessed in interrupt handlers to send an EOI on completion of an interrupt. Currently, the `enable_hardware_interrupts` function will execute an `sti` instruction (enabling interrupts) *before* it initializes the interrupt controller's `InitOnce` cell. This means that if an interrupt occurs immediately after the `sti`, it can cause a race where the static is accessed before it's initialized.
Fixes #383
> fix(hal-x86_64): fix race in interrupt controller init

- hal-core/src/mem/page.rs
- hal-x86_64/src/mm.rs
The `page::Alloc` trait's methods take an `&self` receiver, so page frames can be allocated with a shared reference (allocator impls typically perform internal synchronization). However, the `page::Map` trait's methods that require a page frame allocator take an `&mut` reference to the frame allocator. This is an artifact of an earlier version of the `page::Alloc` trait whose methods had a mutable `&mut self` receiver, but is no longer necessary.
This commit changes the `page::Map` trait to take a shared reference to the page-frame allocator when one is required.
> feat(hal-core): pass page frame allocator immutably

- cordyceps/src/list.rs
Currently, the `cordyceps::List` documentation states the time complexity of certain methods, such as `pop_front`, `pop_back`, `push_front`, and `push_back`, are *O*(*n*), while they are actually *O*(1). This commit fixes the incorrect docs.
Fixes #429
> docs(cordyceps): fix wrong time complexity notes

- maitake/src/scheduler.rs
- maitake/src/task.rs
- maitake/src/task/builder.rs
- maitake/src/task/join_handle.rs
Currently, `maitake`'s scheduler types require tasks to be `Send`. This is because the scheduler itself is `Send` and `Sync`, and it may be ticked from more than one thread/CPU core. Ticking a scheduler which contains `!Send` tasks spawned from one thread on another thread is essentially equivalent to transferring ownership of those `!Send` tasks across threads, so a `Send + Sync` scheduler cannot execute `!Send` futures.
This branch introduces new `LocalScheduler` and `LocalStaticScheduler` types for executing `!Send` futures. Other than the fact that they can spawn futures which are not `Send`, and are themselves not `Send` or `Sync`, they are functionally the same as the existing `Scheduler` and `StaticScheduler` types. Additionally, in order to support other threads to spawn tasks …
> feat(maitake): add local (`!Send`) scheduler types

- maitake/src/time/timer/tests/concurrent.rs
- maitake/src/time/timer/tests/wheel_tests.rs
- maitake/src/util.rs
> Add a test subscriber guard to properly capture tracing messages

- bitfield/src/bitfield.rs
Apparently the tables weren't getting rendered properly by RustDoc...
Before:
After:
> docs(bitfield): replace tables with bulleted lists

- maitake/src/sync/wait_cell.rs
- maitake/src/sync/wait_queue.rs
- maitake/src/time/timer/sleep.rs
- maitake/src/trace.rs
- maitake/src/util.rs
This branch rewrites the `maitake::sync::WaitCell` type a bit to fix
potential lost wakeups accidentally introduced in #453. In addition, it
changes the API a bit:
- Replace `register_wait` with `poll_wait`, which I think is a bit
nicer,
- Removed the `RegisterError::Waking` variant since `poll_wait` returns
`Ready` if the cell was woken, and renamed `RegisterError` to just
`Error`,
- Introduced a `WaitCell::subscribe` method to eagerly pre-register the
task's `Waker` in the `WaitCell`. This is intended to be used to
register the task to be woken *before* performing an operation that
results in a wakeup, such as enabling an interrupt that will wake the
task.
Closes #455
> feat(maitake): add `WaitCell::subscribe` and `poll_wait`

- maitake/src/scheduler.rs
- maitake/tests/scheduler/alloc.rs
- maitake/tests/scheduler/main.rs
In order to allow stealing tasks from blocked cores, don't hold a Consumer for `run_queue` while polling.
I think as-is, this changes the documented behavior:
> Only a single CPU core/thread may tick a given scheduler at a time. If another call to tick is in progress on a different core, this method will wait until that call to tick completes before ticking the scheduler.
and allows interleaving calls to `tick`. Is this a property worth maintaining? I think a lock could be introduced to do so if necessary.
> feat(maitake): dequeue one task at a time in scheduler

- bitfield/README.md
- cordyceps/README.md
- maitake/README.md
This adds a disclaimer to the READMEs of all published crates in the
repo, stating that they are hobby projects I'm working on for fun. This
is intended to communicate the level of support and maintainance that
other users of these crates can reasonably expect.
> docs: hobby project disclaimer for published libs

- bitfield/src/bitfield.rs
- bitfield/src/from_bits.rs
- bitfield/src/pack.rs
This branch adds support for `u128` as a representation for the
`bitfield!` macro, and packing specs for 128-bit numbers.
Closes #466
> feat(bitfield): add `u128` support

- maitake-sync/src/loom.rs
- maitake-sync/src/spin.rs
- maitake-sync/src/spin/rwlock.rs
- maitake-sync/src/util.rs
- maitake-sync/src/util/backoff.rs
- maitake-sync/src/wait_cell.rs
- maitake/src/loom.rs
This commit adds a synchronous `RwLock` spinlock to
`maitake_sync::spin`.
> feat(maitake-sync): add `spin::RwLock`

- Cargo.lock
- hal-x86_64/Cargo.toml
- hal-x86_64/src/interrupt.rs
- hal-x86_64/src/interrupt/apic/local.rs
- hal-x86_64/src/time.rs
- hal-x86_64/src/time/pit.rs
- hal-x86_64/src/time/tsc.rs
- maitake/src/loom.rs
- maitake/src/time.rs
- maitake/src/time/clock.rs
- maitake/src/time/timer.rs
- maitake/src/time/timer/sleep.rs
- maitake/src/time/timer/tests.rs
- maitake/src/time/timer/tests/concurrent.rs
- maitake/src/time/timer/tests/wheel_tests.rs
- maitake/src/time/timer/wheel.rs
- src/arch/x86_64.rs
- src/arch/x86_64/boot.rs
- src/arch/x86_64/interrupt.rs
- src/lib.rs
- src/rt.rs
- src/shell.rs
- trace/Cargo.toml
- trace/src/lib.rs
> improve maitake timer wheel

- maitake-sync/src/wait_cell.rs
- maitake-sync/src/wait_queue.rs
- maitake/src/time/timer/tests.rs
Implementing the interface that @hawkw so wisely suggested
> Add `wait_for` and `wait_for_value` to WaitCell and WaitQueue

- maitake-sync/src/wait_cell.rs
- maitake-sync/src/wait_map.rs
- maitake-sync/src/wait_queue.rs
> [maitake-sync]: Provide "is_closed" methods for WaitCell/WaitMap/WaitQueue

- maitake-sync/src/wait_map.rs
- maitake-sync/src/wait_map/tests/alloc_tests.rs
`maitake-sync`'s `waitmap::Wait` future has an `enqueue` method that
does the same thing as the `subscribe` methods on `WaitCell` and
`WaitQueue`...but has a different name. I think this might be due to
`enqueue` being added earlier or something, or maybe we just weren't
paying attention. Regardless, I figured it was nicer to use the same
name for the method that does the same thing on these different types.
This commit renames the `waitmap::Wait::enqueue` method to `subscribe`,
and the future it returns from `EnqueueWait` to `Subscribe`, analogously
to `WaitQueue` and `WaitCell`. I've left a deprecated type alias and a
deprecated function alias in place, so this isn't a breaking change:
users who reference `Wait::enqueue` or `EnqueueWait` will still be able
to compile their code, but …
> feat(maitake-sync): rename `EnqueueWait` to `Subscribe`

- bitfield/README.md
- cordyceps/README.md
- maitake-sync/README.md
This just seemed kinda nice to add.
> docs: link to changelogs in published crate READMEs

- hal-x86_64/src/interrupt.rs
- hal-x86_64/src/interrupt/idt.rs
MnemOS would like us to provide lower-level access to the IDT in
`hal-x86_64` so that they can work around the nice, high level
abstractions we worked so hard to provide for them (see
tosc-rs/mnemos#337). This PR capitulates to mnemOS' demands by making
the IDT methods for registering raw ISR functions public. I hope mnemOS
doesn't shoot themselves in the foot using this :)
> feat(x86_64): make raw IDT methods public

- hal-x86_64/src/interrupt.rs
- hal-x86_64/src/interrupt/apic.rs
- hal-x86_64/src/interrupt/apic/io.rs
- hal-x86_64/src/interrupt/idt.rs
- hal-x86_64/src/interrupt/pic.rs
Basically, the current way you interact with ISA standard PC interrupts
in the Mycelium x86_64 HAL is nonsensical, in several ways:
1. For some reason, we were mapping the I/O APIC ISA IRQs and the PIC
ISA IRQs to separate regions in the IDT, even though you can only ever
have either an I/O APIC *or* a PIC. Because of this, we were creating
separate entries for each ISA interrupt's ISR in the PIC region and the
I/O APIC region of the IDT. This doesn't actually break anything, but
it's stupid and dumb and I don't know why I did that.
2. I made an attempt to have an interface for controlling ISA interrupts
that abstracts over the I/O APIC and PIC interrupt models. But,
currently, you can't actually *use* this thing to do anything you might
want to do in an abstract way …
> feat(x86_64): real abstraction for ISA IRQs, unfuck I/O APIC

- src/arch/x86_64/shell.rs
- src/shell.rs
This commit adds kernel debug shell commands `dump arch msr` and dump
arch cpuid`, to print the value of x86 model-specific registers and
CPUID leaves, respectively. I also added a bunch of argument-parsing
utilities to the kernel debug shell.
Closes #491
> feat(x86_64): debug commands to print CPUID & MSRs

- hal-x86_64/src/interrupt/apic/local.rs
The local APIC has an ESR (Error Status Register) that can be read to get error bits. This is particularly useful in a handler for the local APIC error interrupt. We don't currently provide an API for looking at this register, so this PR adds one.
> feat(hal-x86_64): add `LocalApic::check_error`

- inoculate/src/qemu.rs
This should make it a bit easier to debug test failures due to guest crashes, I hope...
> feat(inoculate): QEMU debug logging in test mode

- inoculate/src/qemu.rs
Currently, the inoculate test command sets a timeout of 60 seconds, and
abruptly kills QEMU if it takes longer than that. This is no longer
nearly long enough to run our tests. This commit increases the timeout
to 1200 seconds (20 minutes). This is a long time, but our tests take a
while to run, and recall that this timeout applies to booting the kernel
*and running all the tests*, rather than being enforced on a per-test
basis.
We should probably make the timeout much smarter than just "kill the
QEMU process after 20 minutes", and instead do it only if we don't see
any interesting test output, or something. But, this is better than just
always failing test runs because we're stupid about timeouts, I guess.
I also fixed a bug where `--nocapture` disables the test protocol output parsing, …
> inoculate test fixes

- maitake-sync/src/blocking/default_mutex.rs
> fix(maitake-sync): for cs-mutex, enter cs before locking mutex

- maitake-sync/src/wait_map.rs
I was unable to await the `Wait` when using a mutex defined in the `mutex` crate because a trait bound was not met. The current trait impl is not general enough.
> fix(maitake-sync): add proper `ScopedRawMutex` bound to `wait_map::Wait`

- maitake-sync/src/mutex.rs
- maitake-sync/src/mutex/tests.rs
- maitake-sync/src/rwlock/tests.rs
- maitake-sync/src/semaphore/tests.rs
- maitake-sync/src/util.rs
- maitake-sync/src/wait_map/tests.rs
- maitake-sync/src/wait_map/tests/alloc_tests.rs
- maitake-sync/src/wait_queue/tests.rs
- maitake-sync/src/wait_queue/tests/alloc_tests.rs
Depends on #517
As described in #516, this commit adds tests ensuring that `Future` impls are always present for sync primitive future types when using user-provided `ScopedRawMutex`/`RawMutex` impls. This should help protect against future regressions.
Fixes #516
> test(maitake-sync): test futures impl `Future`

- cordyceps/src/lib.rs
- cordyceps/src/sorted_list.rs
- cordyceps/src/stack.rs
This PR implements:
* A new method for `TransferStack` that reports whether the list was previously empty
* A new type, `SortedList`, that is a sorted singly-linked-list
These are changes I am making for experimentation with embassy's scheduler, which I am using `cordyceps` for.
These changes are currently functional and minimally tested, but probably could use tweaks to better fit naturally in the library.
> feat(cordyceps): singly-linked intrusive `SortedList`

- maitake-sync/README.md
> docs: typo fix

- .github/workflows/ci.yml
- cordyceps/README.md
- cordyceps/src/lib.rs
- cordyceps/src/mpsc_queue.rs
- cordyceps/src/stack.rs
- cordyceps/src/util.rs
This PR is a first attempt to allow building of `cordyceps` on non-CAS enabled targets, such as `thumbv6m-none-eabi`/Cortex-M0+/rp2040.
Doing this as a first feature, prior to implementing a non-atomic and `critical_section` based version of TransferStack, in service of https://github.com/embassy-rs/embassy/pull/4035.
Rather than making a default-on "CAS" feature, we instead gate on `cfg(target_has_atomic = "ptr")`, which was [stabilized in 1.60](https://github.com/rust-lang/rust/pull/93824), which currently has the meaning of "this target has CAS". This automatically gates-out `TransferStack` and `MpscQueue`, while the "mutable" collections can still be used.
Right now the cfg gating is a little scattershot, I wanted to open this to discuss, if you'd like me to clean things up a bit to …
> feat(cordyceps): Initial support for non-CAS targets

- cordyceps/src/list.rs
- cordyceps/src/list/tests.rs
- cordyceps/src/list/tests/iter_raw.rs
closes #532
cc https://github.com/tweedegolf/cfg-noodle/issues/9
This is an initial implementation of a "raw" iterator, that allows for type-punning of nodes of a `List`. Unlike `MpscQueue` and `TransferStack`, which give back `T::Handle` elements, the `iter()` and `iter_mut()` methods of `List` instead give `&T` or `Pin<&mut T>`. However, by creating these references, we narrow the provenance of the reference to only the header of a type-punned object, leading to miri stacked borrow violations.
Ideally, we would be able to provide an iterator over something like `&T::Handle`, as we don't want to necessarily give ownership (which `T::Handle` semantically has), but this is difficult to express in an iterator, as we would need to store the `T::Handle` somewhere, and forget it so we don't …
> cordyceps: Add "raw" iter for `List`

- cordyceps/src/list.rs
- cordyceps/src/stack.rs
also rustfmt deleted an extra line in list.rs.
> feat(cordyceps): add `Stack::push_was_empty` method to match TransferStack's API

- maitake/README.md
The markdown table of feature flags in the `maitake` docs was fucked up. This unfucks it.
It used to look like this:
Now it looks normal:
> docs(maitake): unfuck features table markdown

- trace/src/lib.rs
i've got a sneaking suspicion that in the serial context the ANSI control characters are taking up invisible space, which definitely makes #493 look way goofier than it should:
but at least with this the above doesn't send the kernel off into a spin? anyway this seems to do the needful for #550.
> write_str loop should terminate
